config/routes.rb
Rails.application.routes.draw do
 
  # resources :products_import, only: [:new, :create]
  resources :products do
    collection { post :import } 
  end

  get 'users/show'
  devise_for :users 
  root to: 'welcome#home'



  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create]
      resources :products, only: [:create]
      resources :sessions, only: [:create]
      delete '/sign_out' , to: 'sessions#destroy'
    end
  end

  
end

app/models/product.rb
require 'csv'
class Product < ApplicationRecord

  # Import CSV, Find or Create product by its title.description
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      products_hash = row.to_hash
      product = Product.create(name: products_hash['name'], price: products_hash['price'], description: products_hash['description'] )
    end
  end

end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < Api::V1::BaseController

    before_action :verify_auth_token, except: [:create]
    before_action :set_product, only: [:show, :update]

  
    def create
      @product = Product.new(product_params)
      if @product.save
        json_response('success', "1", Api::V1::ProductSerializer.new(@product).serializable_hash[:data][:attributes])
      else
        render_json({message: ErrorDecorator.new(@user).display_errors, rstatus: 0}.to_json)
      end
    end

  
    private

    def set_product
      @product = Product.find_by_id(params[:id])
    end

    def product_params
      params.permit(:name, :description, :price)
    end
  
  
  end
  
  

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all   
  end

  def show; end
  
  def new
    @product = Product.new
  end

  def edit; end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "Product was created successfully"
      redirect_to @product
    else
      render :new 
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product
      flash[:success] = "Product was successfully updated"
    else
      render :edit
    end
  end


  def destroy
    @product.destroy
    flash[:notice] ='Product was successfully destroyed.' 
    redirect_to products_path
  end


  def import
    Product.import(params[:file])
    redirect_to products_path, notice: "Product Uploaded successfully"
   end

  private

    def set_product
      @product = Product.find_by_id(params[:id])
      redirect_to products_path if @product.blank?
    end

    def product_params
      params.require(
        :product
      ).permit(
        :name,
        :description,
        :price
      )
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="well border-blue" style="background: whitesmoke;">

  <h4>Products</h4>
  <div class= "btn btn-primary" >
  <%= form_tag import_products_path, multipart: true do%>
      <div> 
        <%= file_field_tag :file %>
      </div>
      <div>
       <%= submit_tag 'Import CSV'%>
      </div> 
    <% end %>
  </div>
</div> 

<div class="well border-blue" >
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Description</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <tr class="well border-blue" style="background: whitesmoke;">
          <td><%= product.name %></td>
          <td><%= product.price %></td>
          <td><%= product.description %></td>
          <td><%= link_to 'Show', product %></td>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
</div>

app/views/products/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4"> 
    <h1> Create Product</h1>
    

      <%= render 'form', product: @product %>

      <%= link_to 'Back', products_path %>
  </div>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>