config/routes.rb
Rails.application.routes.draw do
 
  # resources :products_import, only: [:new, :create]
  resources :products do
    collection { post :import } 
  end

  get 'users/show'
  devise_for :users 
  root to: 'welcome#home'



  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create]
      resources :products, only: [:create]
      resources :sessions, only: [:create]
      delete '/sign_out' , to: 'sessions#destroy'
    end
  end

  
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
    <%= link_to "PRODUCT MANAGEMENT", root_url, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li>Logged in as <%= current_user.email %></li>
            <li><%= link_to "All Products", products_path %></li>
            <li><%= link_to "Create Products", new_product_path %></li>
            <li><%= link_to "Profile", users_show_path %></li>
            <li><%= link_to "Settings", edit_user_registration_path %></li>
            <li><%= link_to "log out", destroy_user_session_path, method: "delete"  %></li>
        <% else %>
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
    </div>
  </header>
  
  
   
  
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FbApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body >
    <%= render 'layouts/header' %>
    <div class="container main-content">
      <% flash.each do |message_type, message| %>
        <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
        <% end %>
      <% end %>
      <%= yield %>  
    </div>
  </body>
  
</html>